#!./sfakeroot sh

for test in chmod chown fchown fchownat lchown stat fstat lstat fstatat statx
do
    tests/$test
    e=$?
    if [ $e -ne 0 ]
    then
        echo "\033[31;1mTest '$test' failed\033[0m"
        exit 1
    else
        echo "\033[255;1mTest '$test' passed!\033[0m"
    fi
done
